version: "3.9"

services:
  postgres:
    image: postgres
    container_name: skill-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skills_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: skill-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
  esdata: